# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
    - '*'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: copy environment
      run: cp .env.example .env
    - name: container build
      run: docker-compose build
    - name: container up
      run: docker-compose up -d
    - name: code quality test
      run: |
        docker-compose exec -T api flake8 .
        docker-compose exec -T api black --check .
        docker-compose exec -T api mypy .
    - name: test with pytest
      run: docker-compose exec -T api pytest -v .
